# Generated by Django 4.0 on 2023-03-12 06:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('consortium', '0010_alter_consortium_consortium_logo'),
        ('secretariat', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='secretariat',
            name='consortium',
        ),
        migrations.AddField(
            model_name='secretariat',
            name='consortium',
            field=models.ManyToManyField(blank=True, to='consortium.Consortium'),
        ),
    ]
