# Generated by Django 4.0 on 2023-03-12 06:11

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('consortium', '0010_alter_consortium_consortium_logo'),
        ('secretariat', '0002_remove_secretariat_consortium_secretariat_consortium'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='secretariat',
            name='consortium',
        ),
        migrations.AddField(
            model_name='secretariat',
            name='consortium',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='+', to='consortium.consortium'),
            preserve_default=False,
        ),
    ]
