# Generated by Django 4.0 on 2023-04-04 02:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('secretariat', '0003_remove_secretariat_consortium_secretariat_consortium'),
    ]

    operations = [
        migrations.AlterField(
            model_name='secretariat',
            name='sex',
            field=models.CharField(choices=[('Female', 'Female'), ('Male', 'Male')], default='Female', max_length=10),
        ),
    ]
