# Generated by Django 4.0 on 2023-04-12 07:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('secretariat', '0004_alter_secretariat_sex'),
    ]

    operations = [
        migrations.AlterField(
            model_name='secretariat',
            name='mname',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
