# Generated by Django 4.0 on 2023-04-13 03:18

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('secretariat', '0005_alter_secretariat_mname'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='secretariat',
            name='consortium',
        ),
    ]
