# Generated by Django 4.0 on 2023-04-14 06:11

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('consortium', '0020_cmi_consortium_id_alter_cmi_is_cmi'),
        ('secretariat', '0006_remove_secretariat_consortium'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='secretariat',
            name='address',
        ),
        migrations.AddField(
            model_name='secretariat',
            name='consortium_id',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='+', to='consortium.consortium'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='secretariat',
            name='date_appointed',
            field=models.DateField(blank=True, null=True),
        ),
    ]
