# Generated by Django 4.0 on 2023-03-09 03:16

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('program', '0003_program_consortium'),
        ('auth_user', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Team',
            fields=[
                ('member_id', models.AutoField(primary_key=True, serialize=False)),
                ('fname', models.CharField(max_length=100)),
                ('lname', models.CharField(max_length=100)),
                ('mname', models.CharField(max_length=100)),
                ('position', models.CharField(max_length=100)),
                ('email_add', models.CharField(max_length=100)),
                ('contact_no', models.CharField(max_length=20)),
                ('date_appointed', models.DateField(blank=True, null=True)),
                ('dob', models.DateField(blank=True, null=True)),
                ('sex', models.CharField(blank=True, max_length=10, null=True)),
                ('bach_deg', models.CharField(blank=True, max_length=100, null=True)),
                ('bdyearcompleted', models.TextField(blank=True, null=True)),
                ('mas_deg', models.CharField(blank=True, max_length=100, null=True)),
                ('mdyearcompleted', models.TextField(blank=True, null=True)),
                ('doc_deg', models.CharField(blank=True, max_length=100, null=True)),
                ('ddyearcompleted', models.TextField(blank=True, null=True)),
                ('specialization', models.CharField(blank=True, max_length=255, null=True)),
                ('photo', models.ImageField(blank=True, null=True, upload_to='team_photo/')),
                ('pds_file', models.FileField(blank=True, null=True, upload_to='pds_files/')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('modified_at', models.DateTimeField(auto_now=True)),
                ('agency', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='+', to='program.agency')),
                ('created_by', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='+', to='auth_user.user')),
                ('modified_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='+', to='auth_user.user')),
            ],
            options={
                'db_table': 'team',
            },
        ),
    ]
