# Generated by Django 4.0 on 2023-03-13 02:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('team', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='team',
            name='bdyearcompleted',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='team',
            name='ddyearcompleted',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='team',
            name='mdyearcompleted',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
