# Generated by Django 4.0 on 2023-03-15 00:03

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('program', '0011_programbudget'),
        ('team', '0002_alter_team_bdyearcompleted_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='team',
            name='agency',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='agency', to='program.agency'),
        ),
    ]
