# Generated by Django 4.0 on 2023-03-16 23:01

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('team', '0004_remove_team_agency_team_cmi'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='team',
            name='bach_deg',
        ),
        migrations.RemoveField(
            model_name='team',
            name='bdyearcompleted',
        ),
        migrations.RemoveField(
            model_name='team',
            name='ddyearcompleted',
        ),
        migrations.RemoveField(
            model_name='team',
            name='dob',
        ),
        migrations.RemoveField(
            model_name='team',
            name='doc_deg',
        ),
        migrations.RemoveField(
            model_name='team',
            name='mas_deg',
        ),
        migrations.RemoveField(
            model_name='team',
            name='mdyearcompleted',
        ),
    ]
