# Generated by Django 4.0 on 2023-04-04 02:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('team', '0006_alter_team_cmi'),
    ]

    operations = [
        migrations.AlterField(
            model_name='team',
            name='sex',
            field=models.CharField(choices=[('Female', 'Female'), ('Male', 'Male')], default='Female', max_length=10),
        ),
    ]
