# Generated by Django 4.0 on 2023-04-07 12:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('team', '0008_remove_team_email_add_team_teams'),
    ]

    operations = [
        migrations.AddField(
            model_name='team',
            name='email_add',
            field=models.CharField(default=1, max_length=100),
            preserve_default=False,
        ),
    ]
