# Generated by Django 4.0 on 2023-04-10 11:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('team', '0009_team_email_add'),
    ]

    operations = [
        migrations.AlterField(
            model_name='team',
            name='teams',
            field=models.CharField(choices=[('RRDCC', 'RRDCC'), ('R&DC', 'R&DC'), ('TTCadaada', 'TTCs'), ('SCC', 'SCC'), ('ICTC', 'ICTC')], default='RRDCC', max_length=10),
        ),
    ]
