# Generated by Django 4.0 on 2023-04-10 11:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('team', '0010_alter_team_teams'),
    ]

    operations = [
        migrations.AlterField(
            model_name='team',
            name='teams',
            field=models.CharField(choices=[('Regional Research and Development Coordinating Committee', 'RRDCC'), ('Research and Development Cluster', 'R&DC'), ('Technology Transfer Cluster', 'TTC'), ('Science Communication Cluster', 'SCC'), ('Information and Communications Technology Cluster', 'ICTC')], default='Regional Research and Development Coordinating Committee', max_length=60),
        ),
    ]
