# Generated by Django 4.0 on 2023-04-13 03:18

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('consortium', '0013_cmi_remove_consortium_created_by_and_more'),
        ('team', '0013_alter_team_teams'),
    ]

    operations = [
        migrations.AlterField(
            model_name='team',
            name='cmi',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='team', to='consortium.cmi', verbose_name='CMI'),
        ),
    ]
