# Generated by Django 4.0 on 2023-03-08 13:10

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('consortium', '0008_alter_consortium_modified_by'),
        ('auth_user', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Agency',
            fields=[
                ('agency_id', models.AutoField(primary_key=True, serialize=False)),
                ('agency_code', models.CharField(max_length=50)),
                ('name', models.CharField(max_length=200)),
                ('iscmi', models.BooleanField(default=True)),
                ('address', models.CharField(max_length=100)),
                ('geolat', models.FloatField(blank=True, null=True)),
                ('geolong', models.FloatField(blank=True, null=True)),
                ('contact_no', models.CharField(max_length=20)),
                ('logo', models.ImageField(blank=True, null=True, upload_to='agency_logos/')),
                ('detail', models.TextField(blank=True, null=True)),
                ('telno', models.CharField(blank=True, max_length=20, null=True)),
                ('email', models.CharField(blank=True, max_length=100, null=True)),
                ('url', models.CharField(blank=True, max_length=255, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('modified_at', models.DateTimeField(auto_now=True)),
                ('consortium', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='+', to='consortium.consortium')),
                ('created_by', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='+', to='auth_user.user')),
                ('modified_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='+', to='auth_user.user')),
            ],
            options={
                'db_table': 'agency',
            },
        ),
        migrations.CreateModel(
            name='Researcher',
            fields=[
                ('researcher_id', models.AutoField(primary_key=True, serialize=False)),
                ('fname', models.CharField(max_length=100)),
                ('lname', models.CharField(max_length=100)),
                ('mname', models.CharField(max_length=100)),
                ('address', models.CharField(blank=True, max_length=100, null=True)),
                ('email', models.CharField(max_length=100)),
                ('contact_no', models.CharField(blank=True, max_length=20, null=True)),
                ('dob', models.DateField(blank=True, null=True)),
                ('sex', models.CharField(max_length=10)),
                ('bach_deg', models.CharField(blank=True, max_length=100, null=True)),
                ('bdyearcompleted', models.IntegerField(blank=True, null=True)),
                ('mas_deg', models.CharField(blank=True, max_length=100, null=True)),
                ('mdyearcompleted', models.IntegerField(blank=True, null=True)),
                ('doc_deg', models.CharField(blank=True, max_length=100, null=True)),
                ('ddyearcompleted', models.IntegerField(blank=True, null=True)),
                ('specialization', models.CharField(blank=True, max_length=255, null=True)),
                ('photo', models.ImageField(blank=True, null=True, upload_to='researcher_photo/')),
                ('pds_file', models.FileField(blank=True, null=True, upload_to='researcher_pds/')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('modified_at', models.DateTimeField(auto_now=True)),
                ('agency', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='+', to='program.agency')),
                ('created_by', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='+', to='auth_user.user')),
                ('modified_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='+', to='auth_user.user')),
            ],
            options={
                'db_table': 'researcher',
            },
        ),
        migrations.CreateModel(
            name='Program',
            fields=[
                ('prog_id', models.AutoField(primary_key=True, serialize=False)),
                ('title', models.CharField(max_length=255)),
                ('prog_description', models.TextField(blank=True, null=True)),
                ('start_date', models.DateField(blank=True, null=True)),
                ('duration', models.IntegerField()),
                ('final_impl_date', models.DateField(blank=True, null=True)),
                ('total_budget', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True)),
                ('daterequestedext', models.DateField(blank=True, null=True)),
                ('ext_duration', models.IntegerField(blank=True, null=True)),
                ('date_uploaded', models.DateField(blank=True, null=True)),
                ('status', models.CharField(blank=True, max_length=100, null=True)),
                ('prog_file', models.FileField(blank=True, null=True, upload_to='prog_files/')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('modified_at', models.DateTimeField(auto_now=True)),
                ('created_by', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='+', to='auth_user.user')),
                ('funding_agency', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='+', to='program.agency')),
                ('impl_agency', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='+', to='program.agency')),
                ('modified_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='+', to='auth_user.user')),
                ('program_leader', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='+', to='program.researcher')),
                ('requested_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='+', to='program.researcher')),
            ],
            options={
                'db_table': 'program',
            },
        ),
    ]
