# Generated by Django 4.0 on 2023-03-08 13:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('program', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='program',
            name='status',
            field=models.CharField(choices=[('ongoing', 'ongoing'), ('finished', 'finished')], default='ongoing', max_length=100),
        ),
    ]
