# Generated by Django 4.0 on 2023-03-08 15:13

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('consortium', '0008_alter_consortium_modified_by'),
        ('program', '0002_alter_program_status'),
    ]

    operations = [
        migrations.AddField(
            model_name='program',
            name='consortium',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='+', to='consortium.consortium'),
        ),
    ]
