# Generated by Django 4.0 on 2023-03-11 12:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('program', '0003_program_consortium'),
    ]

    operations = [
        migrations.AddField(
            model_name='program',
            name='co_impl_agency',
            field=models.ManyToManyField(blank=True, null=True, related_name='+', to='program.Agency'),
        ),
    ]
