# Generated by Django 4.0 on 2023-03-11 13:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('program', '0006_alter_program_co_impl_agency'),
    ]

    operations = [
        migrations.AlterField(
            model_name='program',
            name='co_impl_agency',
            field=models.ManyToManyField(to='program.Agency'),
        ),
    ]
