# Generated by Django 4.0 on 2023-03-12 07:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('commodity', '0001_initial'),
        ('program', '0009_stakeholder'),
    ]

    operations = [
        migrations.AddField(
            model_name='program',
            name='commodity',
            field=models.ManyToManyField(blank=True, to='commodity.Commodity'),
        ),
    ]
