# Generated by Django 4.0 on 2023-03-16 15:39

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('consortium', '0010_alter_consortium_consortium_logo'),
        ('program', '0011_programbudget'),
    ]

    operations = [
        migrations.AlterField(
            model_name='program',
            name='consortium',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='programs', to='consortium.consortium'),
        ),
    ]
