# Generated by Django 4.0 on 2023-03-20 10:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('program', '0012_alter_program_consortium'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='researcher',
            name='bach_deg',
        ),
        migrations.RemoveField(
            model_name='researcher',
            name='bdyearcompleted',
        ),
        migrations.RemoveField(
            model_name='researcher',
            name='ddyearcompleted',
        ),
        migrations.RemoveField(
            model_name='researcher',
            name='doc_deg',
        ),
        migrations.RemoveField(
            model_name='researcher',
            name='mas_deg',
        ),
        migrations.RemoveField(
            model_name='researcher',
            name='mdyearcompleted',
        ),
        migrations.AlterField(
            model_name='programbudget',
            name='progbdg_id',
            field=models.AutoField(primary_key=True, serialize=False),
        ),
    ]
