# Generated by Django 4.0 on 2023-03-24 14:14

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('consortium', '0011_consortium_consortium_acronym'),
        ('program', '0014_alter_programbudget_yr'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='agency',
            name='consortium',
        ),
        migrations.RemoveField(
            model_name='agency',
            name='created_by',
        ),
        migrations.RemoveField(
            model_name='agency',
            name='modified_by',
        ),
        migrations.RemoveField(
            model_name='researcher',
            name='agency',
        ),
        migrations.AddField(
            model_name='researcher',
            name='cmi',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='+', to='consortium.consortium'),
        ),
        migrations.AlterField(
            model_name='program',
            name='co_impl_agency',
            field=models.ManyToManyField(blank=True, to='consortium.Consortium'),
        ),
        migrations.AlterField(
            model_name='program',
            name='funding_agency',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='+', to='consortium.consortium'),
        ),
        migrations.AlterField(
            model_name='program',
            name='impl_agency',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='+', to='consortium.consortium'),
        ),
        migrations.AlterField(
            model_name='programbudget',
            name='fund_source',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='+', to='consortium.consortium'),
        ),
    ]
