# Generated by Django 4.0 on 2023-03-24 14:14

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('program', '0015_remove_agency_consortium_remove_agency_created_by_and_more'),
        ('project', '0003_alter_project_co_impl_agency_and_more'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Agency',
        ),
    ]
