# Generated by Django 4.0 on 2023-04-04 02:37

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('commodity', '0009_alter_commodity_img'),
        ('program', '0017_alter_program_status'),
    ]

    operations = [
        migrations.AlterField(
            model_name='program',
            name='commodity',
            field=models.ManyToManyField(blank=True, related_name='prog_com', to='commodity.Commodity'),
        ),
        migrations.AlterField(
            model_name='programbudget',
            name='prog_id',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='prog_budg', to='program.program'),
        ),
    ]
