# Generated by Django 4.0 on 2023-04-10 11:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('program', '0018_alter_program_commodity_alter_programbudget_prog_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='researcher',
            name='sex',
            field=models.CharField(choices=[('Female', 'Female'), ('Male', 'Male')], default='Female', max_length=10),
        ),
        migrations.AlterField(
            model_name='stakeholder',
            name='sex',
            field=models.CharField(choices=[('Female', 'Female'), ('Male', 'Male')], default='Female', max_length=10),
        ),
    ]
