# Generated by Django 4.0 on 2023-04-12 07:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('program', '0019_alter_researcher_sex_alter_stakeholder_sex'),
    ]

    operations = [
        migrations.AlterField(
            model_name='researcher',
            name='mname',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='stakeholder',
            name='mname',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
