# Generated by Django 4.0 on 2023-04-12 09:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('program', '0020_alter_researcher_mname_alter_stakeholder_mname'),
    ]

    operations = [
        migrations.AlterField(
            model_name='programbudget',
            name='eo',
            field=models.TextField(blank=True, null=True),
        ),
    ]
