# Generated by Django 4.0 on 2023-04-12 09:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('program', '0021_alter_programbudget_eo'),
    ]

    operations = [
        migrations.AlterField(
            model_name='programbudget',
            name='eo',
            field=models.FloatField(blank=True, null=True),
        ),
    ]
