# Generated by Django 4.0 on 2023-04-13 09:36

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('consortium', '0016_alter_cmi_contact_no'),
        ('program', '0023_remove_program_consortium_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='program',
            name='impl_agency',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='programs', to='consortium.cmi'),
        ),
    ]
