# Generated by Django 4.0 on 2023-05-09 14:18

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('consortium', '0020_cmi_consortium_id_alter_cmi_is_cmi'),
        ('program', '0024_alter_program_impl_agency'),
    ]

    operations = [
        migrations.AlterField(
            model_name='stakeholder',
            name='cmi',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='+', to='consortium.consortium'),
        ),
    ]
