# Generated by Django 4.0 on 2023-05-09 14:21

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('program', '0025_alter_stakeholder_cmi'),
    ]

    operations = [
        migrations.RenameField(
            model_name='stakeholder',
            old_name='cmi',
            new_name='consortium_id',
        ),
    ]
