# Generated by Django 4.0 on 2023-05-17 05:41

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('commodity', '0013_remove_commodity_stakeholder'),
        ('program', '0026_rename_cmi_stakeholder_consortium_id'),
    ]

    operations = [
        migrations.AddField(
            model_name='stakeholder',
            name='commodity',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='adaptor', to='commodity.commodity'),
        ),
    ]
