# Generated by Django 4.0 on 2023-05-17 09:32

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('program', '0027_stakeholder_commodity'),
    ]

    operations = [
        migrations.AlterField(
            model_name='programbudget',
            name='prog_id',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='prog_budg', to='program.program'),
        ),
    ]
