# Generated by Django 4.0 on 2023-05-17 11:31

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('program', '0030_historicalprogram'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='historicalprogram',
            name='created_at',
        ),
        migrations.RemoveField(
            model_name='historicalprogram',
            name='created_by',
        ),
        migrations.RemoveField(
            model_name='historicalprogram',
            name='date_uploaded',
        ),
        migrations.RemoveField(
            model_name='historicalprogram',
            name='duration',
        ),
        migrations.RemoveField(
            model_name='historicalprogram',
            name='ext_duration',
        ),
        migrations.RemoveField(
            model_name='historicalprogram',
            name='final_impl_date',
        ),
        migrations.RemoveField(
            model_name='historicalprogram',
            name='funding_agency',
        ),
        migrations.RemoveField(
            model_name='historicalprogram',
            name='impl_agency',
        ),
        migrations.RemoveField(
            model_name='historicalprogram',
            name='modified_at',
        ),
        migrations.RemoveField(
            model_name='historicalprogram',
            name='modified_by',
        ),
        migrations.RemoveField(
            model_name='historicalprogram',
            name='prog_description',
        ),
        migrations.RemoveField(
            model_name='historicalprogram',
            name='prog_file',
        ),
        migrations.RemoveField(
            model_name='historicalprogram',
            name='requested_by',
        ),
        migrations.RemoveField(
            model_name='historicalprogram',
            name='start_date',
        ),
        migrations.RemoveField(
            model_name='historicalprogram',
            name='status',
        ),
        migrations.RemoveField(
            model_name='historicalprogram',
            name='title',
        ),
        migrations.RemoveField(
            model_name='historicalprogram',
            name='total_budget',
        ),
    ]
