# Generated by Django 4.0 on 2023-05-17 11:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('program', '0031_remove_historicalprogram_created_at_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='historicalprogram',
            name='title',
            field=models.CharField(default=1, max_length=255),
            preserve_default=False,
        ),
    ]
