# Generated by Django 4.0 on 2023-05-28 13:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('program', '0033_alter_program_status'),
    ]

    operations = [
        migrations.AddField(
            model_name='programbudget',
            name='total',
            field=models.CharField(default=21, max_length=100),
            preserve_default=False,
        ),
    ]
