# Generated by Django 4.0 on 2023-05-29 00:58

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('program', '0034_programbudget_total'),
    ]

    operations = [
        migrations.RenameField(
            model_name='stakeholder',
            old_name='fname',
            new_name='first_name',
        ),
        migrations.RenameField(
            model_name='stakeholder',
            old_name='lname',
            new_name='last_name',
        ),
        migrations.RemoveField(
            model_name='program',
            name='total_budget',
        ),
    ]
