# Generated by Django 4.0 on 2023-05-29 15:46

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('program', '0036_rename_first_name_stakeholder_fname_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='stakeholder',
            old_name='fname',
            new_name='first_name',
        ),
        migrations.RenameField(
            model_name='stakeholder',
            old_name='lname',
            new_name='last_name',
        ),
    ]
