# Generated by Django 4.0 on 2023-03-07 13:47

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('consortium', '0003_alter_consortium_modified_by'),
    ]

    operations = [
        migrations.AlterModelTable(
            name='consortium',
            table='consortium',
        ),
    ]
