# Generated by Django 4.0 on 2023-03-10 07:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('consortium', '0008_alter_consortium_modified_by'),
    ]

    operations = [
        migrations.AlterField(
            model_name='consortium',
            name='consortium_logo',
            field=models.ImageField(blank=True, null=True, upload_to='cmi_logos/'),
        ),
    ]
