# Generated by Django 4.0 on 2023-03-11 12:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('consortium', '0009_alter_consortium_consortium_logo'),
    ]

    operations = [
        migrations.AlterField(
            model_name='consortium',
            name='consortium_logo',
            field=models.ImageField(upload_to='cmi_logos/'),
        ),
    ]
