# Generated by Django 4.0 on 2023-03-18 11:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('consortium', '0010_alter_consortium_consortium_logo'),
    ]

    operations = [
        migrations.AddField(
            model_name='consortium',
            name='consortium_acronym',
            field=models.CharField(default=1, max_length=20),
            preserve_default=False,
        ),
    ]
