# Generated by Django 4.0 on 2023-04-13 03:18

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('project', '0008_remove_project_consortium_and_more'),
        ('commodity', '0011_commodity_cmi_name'),
        ('secretariat', '0006_remove_secretariat_consortium'),
        ('consortium', '0013_cmi_remove_consortium_created_by_and_more'),
        ('auth_user', '0002_remove_user_admin'),
        ('team', '0014_alter_team_cmi'),
        ('program', '0023_remove_program_consortium_and_more'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Consortium',
        ),
        migrations.AddField(
            model_name='cmi',
            name='created_by',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='+', to='auth_user.user'),
        ),
        migrations.AddField(
            model_name='cmi',
            name='modified_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='+', to='auth_user.user'),
        ),
    ]
