# Generated by Django 4.0 on 2023-04-13 04:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('consortium', '0014_delete_consortium_cmi_created_by_cmi_modified_by'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='cmi',
            name='is_cmi',
        ),
        migrations.AlterField(
            model_name='cmi',
            name='contact_no',
            field=models.CharField(blank=True, max_length=40, null=True),
        ),
    ]
