# Generated by Django 4.0 on 2023-04-13 09:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('consortium', '0015_remove_cmi_is_cmi_alter_cmi_contact_no'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cmi',
            name='contact_no',
            field=models.CharField(blank=True, max_length=70, null=True),
        ),
    ]
