# Generated by Django 4.0 on 2023-04-13 11:38

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('auth_user', '0002_remove_user_admin'),
        ('consortium', '0016_alter_cmi_contact_no'),
    ]

    operations = [
        migrations.CreateModel(
            name='Consortium',
            fields=[
                ('consortium_id', models.AutoField(primary_key=True, serialize=False)),
                ('consortium_code', models.CharField(max_length=50)),
                ('consortium_name', models.CharField(max_length=255)),
                ('consortium_address', models.CharField(max_length=255)),
                ('geolat', models.FloatField(blank=True, null=True)),
                ('geolong', models.FloatField(blank=True, null=True)),
                ('consortium_logo', models.ImageField(upload_to='consortium_logos/')),
                ('mission', models.TextField(blank=True, null=True)),
                ('vision', models.TextField(blank=True, null=True)),
                ('consortium_desc', models.TextField(blank=True, null=True)),
                ('consortium_objectives', models.TextField(blank=True, null=True)),
                ('url', models.URLField(blank=True, max_length=255, null=True)),
                ('fb_url', models.URLField(blank=True, max_length=255, null=True)),
                ('yt_url', models.URLField(blank=True, max_length=255, null=True)),
                ('telno', models.CharField(blank=True, max_length=100, null=True)),
                ('email', models.CharField(blank=True, max_length=100, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('modified_at', models.DateTimeField(auto_now=True)),
                ('created_by', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='+', to='auth_user.user')),
                ('modified_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='+', to='auth_user.user')),
            ],
            options={
                'db_table': 'consortium',
            },
        ),
    ]
