# Generated by Django 4.0 on 2023-04-14 05:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('consortium', '0018_cmi_status'),
    ]

    operations = [
        migrations.AddField(
            model_name='cmi',
            name='is_cmi',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='cmi',
            name='remarks',
            field=models.TextField(blank=True, null=True),
        ),
    ]
