# Generated by Django 4.0 on 2023-04-14 05:45

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('consortium', '0019_cmi_is_cmi_cmi_remarks'),
    ]

    operations = [
        migrations.AddField(
            model_name='cmi',
            name='consortium_id',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='+', to='consortium.consortium'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='cmi',
            name='is_cmi',
            field=models.BooleanField(default=True),
        ),
    ]
