# Generated by Django 4.0 on 2023-03-24 14:14

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('consortium', '0011_consortium_consortium_acronym'),
        ('project', '0002_alter_priorityarea_description_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='project',
            name='co_impl_agency',
            field=models.ManyToManyField(blank=True, related_name='co_impl_agency', to='consortium.Consortium'),
        ),
        migrations.AlterField(
            model_name='project',
            name='coop_agency',
            field=models.ManyToManyField(blank=True, related_name='coop_agency', to='consortium.Consortium'),
        ),
        migrations.AlterField(
            model_name='project',
            name='fund_agency',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='+', to='consortium.consortium'),
        ),
        migrations.AlterField(
            model_name='project',
            name='impl_agency',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='+', to='consortium.consortium'),
        ),
    ]
