# Generated by Django 4.0 on 2023-04-01 11:45

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('program', '0017_alter_program_status'),
        ('consortium', '0011_consortium_consortium_acronym'),
        ('project', '0004_alter_project_proj_leader_alter_project_status'),
    ]

    operations = [
        migrations.AlterField(
            model_name='project',
            name='consortium',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='projects', to='consortium.consortium'),
        ),
        migrations.AlterField(
            model_name='project',
            name='prog_id',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='proj_prog', to='program.program'),
        ),
    ]
