# Generated by Django 4.0 on 2023-04-13 03:18

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('consortium', '0013_cmi_remove_consortium_created_by_and_more'),
        ('project', '0007_alter_project_title'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='project',
            name='consortium',
        ),
        migrations.AlterField(
            model_name='priorityarea',
            name='description',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='project',
            name='co_impl_agency',
            field=models.ManyToManyField(blank=True, related_name='co_impl_agency', to='consortium.CMI'),
        ),
        migrations.AlterField(
            model_name='project',
            name='coop_agency',
            field=models.ManyToManyField(blank=True, related_name='coop_agency', to='consortium.CMI'),
        ),
        migrations.AlterField(
            model_name='project',
            name='fund_agency',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='+', to='consortium.cmi'),
        ),
        migrations.AlterField(
            model_name='project',
            name='impl_agency',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='projects', to='consortium.cmi'),
        ),
    ]
