# Generated by Django 4.0 on 2023-05-09 15:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('project', '0009_alter_project_title'),
    ]

    operations = [
        migrations.AlterField(
            model_name='projectimplementingsite',
            name='city',
            field=models.CharField(default=1, max_length=100),
            preserve_default=False,
        ),
    ]
