# Generated by Django 4.0 on 2023-05-17 05:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('project', '0010_alter_projectimplementingsite_city'),
    ]

    operations = [
        migrations.AlterField(
            model_name='projectimplementingsite',
            name='barangay',
            field=models.CharField(default=1, max_length=100),
            preserve_default=False,
        ),
    ]
