# Generated by Django 4.0 on 2023-03-16 13:18

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('consortium', '0010_alter_consortium_consortium_logo'),
        ('commodity', '0003_alter_commodity_consortium_name_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='commodity',
            name='consortium_name',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='commodities', to='consortium.consortium'),
        ),
    ]
