# Generated by Django 4.0 on 2023-03-19 06:24

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('commodity', '0004_alter_commodity_consortium_name'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='commodity',
            name='iec_id',
        ),
        migrations.AddField(
            model_name='iecmaterial',
            name='commodity',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='iecmaterial', to='commodity.commodity'),
        ),
    ]
