# Generated by Django 4.0 on 2023-03-21 02:37

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('consortium', '0011_consortium_consortium_acronym'),
        ('commodity', '0007_alter_iecmaterial_commodity'),
    ]

    operations = [
        migrations.AlterField(
            model_name='commodity',
            name='consortium_name',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='commodities', to='consortium.consortium', verbose_name='CMI'),
        ),
    ]
