# Generated by Django 4.0 on 2023-04-13 03:18

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('commodity', '0010_remove_commodity_consortium_name'),
        ('consortium', '0013_cmi_remove_consortium_created_by_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='commodity',
            name='cmi_name',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='commodities', to='consortium.cmi', verbose_name='CMI'),
            preserve_default=False,
        ),
    ]
