# Generated by Django 4.0 on 2023-05-09 14:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('program', '0026_rename_cmi_stakeholder_consortium_id'),
        ('commodity', '0011_commodity_cmi_name'),
    ]

    operations = [
        migrations.AddField(
            model_name='commodity',
            name='stakeholder',
            field=models.ManyToManyField(to='program.Stakeholder'),
        ),
    ]
