# Generated by Django 4.0 on 2023-05-17 05:41

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('commodity', '0012_commodity_stakeholder'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='commodity',
            name='stakeholder',
        ),
    ]
